export const AUTOK = [
  {
    ar: 22000000,
    db: 1,
    kosarKep: "./kepek/m4_kosar.jpg",
    termek: "BMW M4",
    teljesitmeny: "140 kW (190 LE)",
    hajtastipus: "xDrive",
    co2: "138 g/km",
    fogyasztas: "5,3 l/100km",
    gyorsulas: "7,4s (0-100 km/h)",
    sebessegvalto: "Automata",
    uzemanyagtipus: "Dízel",
    kep: "./kepek/BMW_4.jpg",
  },
  {
    ar: 25000000,
    db: 1,
    kosarKep: "./kepek/m5_kosar.jpg",
    termek: "BMW M5 Limousine",
    teljesitmeny: "215 kW (292 LE)",
    hajtastipus: "xDrive",
    co2: "147 g/km",
    fogyasztas: "5,6 l/100km",
    gyorsulas: "5,9s (0-100 km/h)",
    sebessegvalto: "Automata",
    uzemanyagtipus: "Hibrid benzin",
    kep: "./kepek/BMW_5.jpg",
  },
  {
    ar: 38000000,
    db: 1,
    kosarKep: "./kepek/m8_kosar.jpg",
    termek: "BMW M8 Coupé",
    teljesitmeny: "390 kW (530 LE)",
    hajtastipus: "xDrive",
    co2: "240 g/km",
    fogyasztas: "10,5 l/100km",
    gyorsulas: "3,9s (0-100 km/h)",
    sebessegvalto: "Automata",
    uzemanyagtipus: "Benzin",
    kep: "./kepek/BMW_8.jpg",
  },
  {
    ar: 46000000,
    db: 1,
    kosarKep: "./kepek/x6_kosar.jpg",
    termek: "BMW X6",
    teljesitmeny: "250 kW (340 LE)",
    hajtastipus: "xDrive",
    co2: "197 g/km",
    fogyasztas: "7,5 l/100km",
    gyorsulas: "5,5s (0-100 km/h)",
    sebessegvalto: "Automata",
    uzemanyagtipus: "Dízel",
    kep: "./kepek/BMW_X6M.jpg",
  },
  {
    ar: 45000000,
    db: 1,
    kosarKep: "./kepek/x7_kosar.jpg",
    termek: "BMW X7",
    teljesitmeny: "250 kW (340 LE)",
    hajtastipus: "xDrive",
    co2: "208 g/km",
    fogyasztas: "7,9 l/100km",
    gyorsulas: "5,9s (0-100 km/h)",
    sebessegvalto: "Automata",
    uzemanyagtipus: "Dízel",
    kep: "./kepek/BMW_X7.jpg",
  },
];

export const FELHASZNALO = [];
